version: '3.7'

# Services
services:

    # Nginx Service
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - ${NGINX_PORT}:80
            - ${PHPMYADMIN_PORT}:8080
        volumes:
            - symfonyvolume:/var/www/symfony:ro
            - phpmyadmindata:/usr/src/phpmyadmin
        depends_on:
            - php
            - phpmyadmin
      
     # PHP Service
    php:
        build: 
            context: .
            dockerfile: .docker/php/Dockerfile
        working_dir: /var/www/symfony
        volumes:
            - symfonyvolume:/var/www/symfony
        #user: ${LOCAL_USER}
        depends_on:
            - mysql
    
    # MySQL Service
    mysql:
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            #- ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - mysqldata:/var/lib/mysql
            
    # PhpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5-fpm-alpine
        environment:
          PMA_HOST: mysql
        volumes:
            - phpmyadmindata:/usr/src/phpmyadmin
        depends_on:
          - mysql
    
    # Scheduler Service
    scheduler:
      build:
            context: .
            dockerfile: .docker/scheduler/Dockerfile
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        #- ./.docker/scheduler/config.ini:/etc/ofelia/config.ini
      depends_on:
        - php
            
# Volumes
volumes:
    mysqldata:
    phpmyadmindata:
    symfonyvolume: